#Copyright 2021, Battelle Energy Alliance, LLC
# file:
#   ./temp/empty.json
# dest:
#   ./temp/output.json
# interface: ens37
plugins:
  network:
    nmap: 127.0.0.1
    # sudo: False
    # nmap_args: -Pn
    # no_host_discovery: True
    # no_services: True
    # do_not_resolve_hosts: True
  # pcap:
  #   file: /tmp/file.pcap
  # cve: True
  # remote:
  #   csv: creds.csv
  #   process: True
  #   hardware: False
  #   filetree: False
  #   directory: /etc
  # openvas:
  #   host: 127.0.0.1
  #   username: admin
  #   password: admin
